version: '3.7'

services:
  api:
    build: 
      context: ./
      args: 
        CI: ENABLED
    entrypoint: bash run.sh
    restart: unless-stopped
    volumes:
    - ./:/fyle-admin-settings-api
    ports:
    - 8007:8007
    depends_on:
    - db
    environment: 
      SECRET_KEY: thisisthedjangosecretkey
      ALLOWED_HOSTS: "*"
      DEBUG: "False"
      API_URL: http://localhost:8007/api
      DATABASE_URL: postgres://postgres:postgres@db:5432/admin_settings
      DB_HOST: db
      FYLE_BASE_URL: https://lolo.fyle.tech
      FYLE_CLIENT_ID: dummy
      FYLE_CLIENT_SECRET: dummy
      FYLE_REFRESH_TOKEN: dummy
      FYLE_TOKEN_URI: https://lolo.fyle.tech
      APP_WK_ORIGIN: https://app.workato.com
      WK_API_PLATFORM_KEY: ""
      WK_PARTNER_EMAIL: ""
      WK_JWT_PRIVATE_KEY: ""
      WK_API_KEY: ""
      WK_CUSTOMER_ID: ""
  db:
    image: "postgres:15"
    environment: 
      POSTGRES_DB: dummy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  api:
  data:
