# Generated by Django 3.1.14 on 2023-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to indentify an Integration', primary_key=True, serialize=False)),
                ('tpa_id', models.CharField(help_text='Third Party App Id', max_length=255)),
                ('tpa_name', models.CharField(help_text='Third Party App Name', max_length=255)),
                ('org_id', models.CharField(help_text='Org Id', max_length=255)),
                ('type', models.CharField(choices=[('ACCOUNTING', 'ACCOUNTING'), ('HRMS', 'HRMS'), ('TRAVEL', 'TRAVEL'), ('PAYROLL', 'PAYROLL')], help_text='Type of Integration', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Is Integration Active')),
                ('is_beta', models.BooleanField(default=False, help_text='Is Beta')),
                ('connected_at', models.DateTimeField(auto_now_add=True, help_text='Connected at datetime')),
                ('disconnected_at', models.DateTimeField(help_text='Disconnected at datetime', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
            ],
            options={
                'db_table': 'integrations',
                'unique_together': {('tpa_id', 'org_id', 'type')},
            },
        ),
    ]
