# Generated by Django 3.1.14 on 2023-08-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('org_id', 'type')},
        ),
    ]
