# Generated by Django 3.1.14 on 2023-11-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20230829_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='is_beta',
            field=models.BooleanField(default=True, help_text='Is Beta'),
        ),
    ]
