# Generated by Django 3.1.14 on 2024-01-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20231129_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='org_name',
            field=models.CharField(help_text='Org Name', max_length=255, null=True),
        ),
    ]
