# Generated by Django 3.1.14 on 2024-02-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_integration_org_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together=set(),
        ),
    ]
