# Generated by Django 4.2.17 on 2025-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_auto_20240223_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='errors_count',
            field=models.IntegerField(default=0, help_text='The number of errors present in the integration'),
        ),
        migrations.AddField(
            model_name='integration',
            name='is_token_expired',
            field=models.BooleanField(default=False, help_text="Whether the integration's access token has expired"),
        ),
    ]
