# Generated by Django 4.2.22 on 2025-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_auto_generated_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='unmapped_card_count',
            field=models.IntegerField(default=0, help_text='The number of unmapped cards present in the integration'),
        ),
    ]
