# Generated by Django 4.2.25 on 2025-10-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_integration_unmapped_card_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='unmapped_employee_count',
            field=models.IntegerField(default=0, help_text='The number of unmapped employees present in the integration'),
        ),
    ]
