# Generated by Django 4.2.25 on 2025-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_integration_unmapped_employee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='has_payment_mode_changed',
            field=models.BooleanField(default=False, help_text='Whether the payment mode has changed from Reimbursable to CCC and vice versa'),
        ),
    ]
