# Generated by Django 3.1.14 on 2023-12-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0004_auto_20230627_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_type', models.CharField(help_text='Type of expense attribute', max_length=255)),
                ('active', models.BooleanField(help_text='Indicates whether the fields is active or not', null=True)),
                ('detail', models.JSONField(help_text='Detailed expense attributes payload', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('source_id', models.CharField(help_text='Fyle ID', max_length=255)),
                ('auto_created', models.BooleanField(default=False, help_text='Indicates whether the field is auto created by the integration')),
                ('org', models.ForeignKey(help_text='Reference to Org model', on_delete=django.db.models.deletion.PROTECT, to='orgs.org')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_type', models.CharField(help_text='Type of expense attribute', max_length=255)),
                ('active', models.BooleanField(help_text='Indicates whether the fields is active or not', null=True)),
                ('detail', models.JSONField(help_text='Detailed destination attributes payload', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('destination_id', models.CharField(help_text='Destination ID', max_length=255)),
                ('auto_created', models.BooleanField(default=False, help_text='Indicates whether the field is auto created by the integration')),
                ('org', models.ForeignKey(help_text='Reference to Org model', on_delete=django.db.models.deletion.PROTECT, to='orgs.org')),
            ],
        ),
    ]
