# Generated by Django 3.1.14 on 2023-12-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_hrms_mappings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationattribute',
            name='value',
            field=models.CharField(help_text='Value of expense attribute', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseattribute',
            name='value',
            field=models.CharField(help_text='Value of expense attribute', max_length=255),
        ),
    ]
