# Generated by Django 3.1.14 on 2023-12-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20230627_1133'),
        ('fyle_hrms_mappings', '0002_auto_20231221_1515'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destinationattribute',
            unique_together={('destination_id', 'attribute_type', 'org')},
        ),
        migrations.AlterUniqueTogether(
            name='expenseattribute',
            unique_together={('value', 'attribute_type', 'org')},
        ),
        migrations.AlterModelTable(
            name='destinationattribute',
            table='destination_attributes',
        ),
        migrations.AlterModelTable(
            name='expenseattribute',
            table='expense_attributes',
        ),
    ]
