# Generated by Django 3.1.14 on 2024-01-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20230627_1133'),
        ('fyle_hrms_mappings', '0003_auto_20231221_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(help_text='Fyle Enum', max_length=255)),
                ('destination_type', models.CharField(help_text='Destination Enum', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping', to='fyle_hrms_mappings.destinationattribute')),
                ('org', models.ForeignKey(help_text='Reference to Org model', on_delete=django.db.models.deletion.PROTECT, to='orgs.org')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping', to='fyle_hrms_mappings.expenseattribute')),
            ],
            options={
                'db_table': 'mappings',
            },
        ),
    ]
