# Generated by Django 3.1.14 on 2024-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_hrms_mappings', '0004_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationattribute',
            name='is_failure_email_sent',
            field=models.BooleanField(default=False, help_text='Indicates whether the failure email is sent'),
        ),
    ]
