# Generated by Django 3.1.14 on 2022-11-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BambooHr',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to indentify a Org', primary_key=True, serialize=False)),
                ('folder_id', models.CharField(help_text='Bamboo HR Folder ID', max_length=255, null=True)),
                ('package_id', models.CharField(help_text='Bamboo HR Package ID', max_length=255, null=True)),
                ('api_token', models.CharField(help_text='Bamboo HR API Token', max_length=255, null=True)),
                ('sub_domain', models.CharField(help_text='Bamboo HR Sub Domain', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('org', models.OneToOneField(help_text='Reference to Org table', on_delete=django.db.models.deletion.PROTECT, to='orgs.org')),
            ],
            options={
                'db_table': 'bamboohr',
            },
        ),
    ]
