# Generated by Django 3.1.14 on 2022-12-01 12:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('bamboohr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to indentify a Configuration', primary_key=True, serialize=False)),
                ('recipe_id', models.CharField(help_text='Recipe Id', max_length=255, null=True)),
                ('start_datetime', models.DateTimeField(help_text='Datetime for start of schedule', null=True)),
                ('interval_hours', models.IntegerField(null=True)),
                ('additional_email_options', models.JSONField(default=list, help_text='Email and Name of person to send email', null=True)),
                ('emails_selected', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Emails Selected For Email Notification', null=True, size=None)),
                ('org', models.OneToOneField(help_text='Reference to Org Table', on_delete=django.db.models.deletion.PROTECT, to='orgs.org')),
            ],
            options={
                'db_table': 'configurations',
            },
        ),
    ]
