# Generated by Django 3.1.14 on 2022-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboohr', '0002_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='configuration',
            name='recipe_status',
            field=models.CharField(help_text='recipe status', max_length=255, null=True),
        ),
    ]
