# Generated by Django 3.1.14 on 2022-12-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamboohr', '0002_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='start_datetime',
        ),
    ]
