# Generated by Django 3.1.14 on 2022-12-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboohr', '0002_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='emails_selected',
        ),
        migrations.AddField(
            model_name='configuration',
            name='emails_selected',
            field=models.JSONField(default=list, help_text='Emails Selected For Email Notification', null=True),
        ),
    ]
