# Generated by Django 3.1.14 on 2022-12-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboohr', '0003_auto_20221201_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='recipe_data',
            field=models.TextField(help_text='Code For Recipe', null=True),
        ),
    ]
