# Generated by Django 3.1.14 on 2022-12-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20221219_1044'),
        ('bamboohr', '0003_auto_20221212_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuration',
            new_name='BambooHrConfiguration',
        ),
        migrations.AlterModelTable(
            name='bamboohrconfiguration',
            table='bamboohr_configurations',
        ),
    ]
