# Generated by Django 3.1.14 on 2023-12-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboohr', '0005_bamboohr_employee_exported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamboohr',
            name='is_credentials_expired',
            field=models.BooleanField(default=False, help_text='BambooHr Credential Status'),
        ),
    ]
