# Generated by Django 3.1.14 on 2024-01-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboohr', '0006_bamboohr_is_credentials_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamboohr',
            name='webhook_id',
            field=models.IntegerField(help_text='ID of the webhook created by BambooHr', null=True),
        ),
    ]
