# Generated by Django 3.1.14 on 2024-01-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboohr', '0007_bamboohr_webhook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamboohr',
            name='private_key',
            field=models.CharField(help_text='Private key to verify webhook calls', max_length=255, null=True),
        ),
    ]
