# Generated by Django 3.1.14 on 2024-02-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamboohr', '0008_bamboohr_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bamboohr',
            name='folder_id',
        ),
        migrations.RemoveField(
            model_name='bamboohr',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='bamboohrconfiguration',
            name='recipe_data',
        ),
        migrations.RemoveField(
            model_name='bamboohrconfiguration',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='bamboohrconfiguration',
            name='recipe_status',
        ),
    ]
