# Generated by Django 3.1.14 on 2023-03-10 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0002_auto_20221219_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='GustoConfiguration',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to indentify a Configuration', primary_key=True, serialize=False)),
                ('recipe_id', models.CharField(help_text='Recipe Id', max_length=255, null=True)),
                ('recipe_data', models.TextField(help_text='Code For Recipe', null=True)),
                ('recipe_status', models.BooleanField(help_text='recipe status', null=True)),
                ('additional_email_options', models.JSONField(default=list, help_text='Email and Name of person to send email', null=True)),
                ('emails_selected', models.JSONField(default=list, help_text='Emails Selected For Email Notification', null=True)),
                ('org', models.OneToOneField(help_text='Reference to Org Table', on_delete=django.db.models.deletion.PROTECT, to='orgs.org')),
            ],
            options={
                'db_table': 'gusto_configurations',
            },
        ),
        migrations.CreateModel(
            name='Gusto',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to indentify a Org', primary_key=True, serialize=False)),
                ('connection_id', models.CharField(help_text='Gusto connection ID to Workato', max_length=100, null=True)),
                ('folder_id', models.CharField(help_text='Gusto Folder ID', max_length=255, null=True)),
                ('package_id', models.CharField(help_text='Gusto Package ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('org', models.OneToOneField(help_text='Reference to Org table', on_delete=django.db.models.deletion.PROTECT, to='orgs.org')),
            ],
            options={
                'db_table': 'gusto',
            },
        ),
    ]
