# Generated by Django 3.1.14 on 2023-03-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gusto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gusto',
            table='gusto',
        ),
        migrations.AlterModelTable(
            name='gustoconfiguration',
            table='gusto_configurations',
        ),
    ]
