# Generated by Django 3.1.14 on 2022-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='is_bamboo_connector',
            field=models.BooleanField(help_text='Is Bamboo Hr Connected', null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='managed_user_id',
            field=models.CharField(help_text='Managed User Id', max_length=255, null=True),
        ),
    ]
