# Generated by Django 3.1.14 on 2022-12-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='is_bamboo_connector',
        ),
    ]
