# Generated by Django 3.1.14 on 2023-06-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20230413_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='allow_travelperk',
            field=models.BooleanField(default=True, help_text='Allow Travelperk'),
        ),
    ]
