# Generated by Django 3.1.14 on 2024-02-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20230627_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='allow_gusto',
        ),
        migrations.RemoveField(
            model_name='org',
            name='allow_travelperk',
        ),
        migrations.RemoveField(
            model_name='org',
            name='is_fyle_connected',
        ),
        migrations.RemoveField(
            model_name='org',
            name='is_sendgrid_connected',
        ),
        migrations.RemoveField(
            model_name='org',
            name='managed_user_id',
        ),
    ]
