# Generated by Django 3.1.14 on 2024-10-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_add_allow_dynamics'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='allow_qbd_direct_integration',
            field=models.BooleanField(default=False, help_text='Allow QBD Direct Integration'),
        ),
    ]
