# Generated by Django 3.1.14 on 2024-12-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_org_allow_qbd_direct_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='allow_dynamics',
            field=models.BooleanField(default=True, help_text='Allow Dynamics'),
        ),
    ]
