# Generated by Django 3.1.14 on 2025-01-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_allow_dynamics_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='allow_qbd_direct_integration',
            field=models.BooleanField(default=True, help_text='Allow QBD Direct Integration'),
        ),
    ]
