# Generated by Django 4.2.20 on 2025-09-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_auto_20250114_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='is_org_rebranded',
            field=models.BooleanField(default=False, help_text='Is Org Rebranded'),
        ),
    ]
