# Generated by Django 4.2.25 on 2025-10-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_org_is_org_rebranded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='is_org_rebranded',
            field=models.BooleanField(default=True, help_text='Is Org Rebranded'),
        ),
    ]
