# Generated by Django 4.2.26 on 2025-12-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_alter_org_is_org_rebranded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='allow_dynamics',
            field=models.BooleanField(default=False, help_text='Allow Dynamics'),
        ),
    ]
