# Generated by Django 4.2.27 on 2026-01-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_alter_org_allow_dynamics'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='allow_bamboohr',
            field=models.BooleanField(default=False, help_text='Allow BambooHR'),
        ),
    ]
