# Generated by Django 3.1.14 on 2023-01-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelperk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelperk',
            name='is_fyle_connected',
            field=models.BooleanField(help_text='If Fyle Account Connected', null=True),
        ),
    ]
