# Generated by Django 3.1.14 on 2023-03-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelperk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelperk',
            name='travelperk_connection_id',
            field=models.IntegerField(help_text='Travelperk Connection Id', null=True),
        ),
    ]
