# Generated by Django 3.1.14 on 2023-04-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelperk', '0003_remove_travelperk_is_fyle_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelperk',
            name='is_travel_perk_connected',
            field=models.BooleanField(help_text='If Travelperk Is Connected', null=True),
        ),
    ]
