# Generated by Django 3.1.14 on 2023-12-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelperk', '0005_invoice_invoicelineitem_travelperkcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelperk',
            name='webhook_enabled',
            field=models.BooleanField(help_text='If Webhook Is Enabled', null=True),
        ),
        migrations.AddField(
            model_name='travelperk',
            name='webhook_subscription_id',
            field=models.CharField(help_text='Webhook Subscription Id', max_length=255, null=True),
        ),
    ]
