# Generated by Django 3.1.14 on 2023-12-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelperk', '0006_auto_20231214_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice_line_id',
            field=models.CharField(default='12312', help_text='id for invoice line', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='vendor',
            field=models.CharField(help_text='Vendor name.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='travelperkconfiguration',
            name='id',
            field=models.AutoField(help_text='def createUnique Id to indentify a Configuration', primary_key=True, serialize=False),
        ),
    ]
