# Generated by Django 3.1.14 on 2024-01-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20230627_1133'),
        ('travelperk', '0008_auto_20240102_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='org_id',
            field=models.ForeignKey(default=1, help_text='Reference to Org table', on_delete=django.db.models.deletion.CASCADE, to='orgs.org'),
            preserve_default=False,
        ),
    ]
