# Generated by Django 3.1.14 on 2024-01-22 20:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20230627_1133'),
        ('travelperk', '0008_auto_20240102_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelperkAdvanceSetting',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to indentify a Advance Settings', primary_key=True, serialize=False)),
                ('default_employee_name', models.CharField(help_text='Default Employee Name', max_length=255, null=True)),
                ('default_employee_id', models.CharField(help_text='Default Employee Id', max_length=255, null=True)),
                ('default_category_name', models.CharField(help_text='Default Category Name', max_length=255, null=True)),
                ('default_category_id', models.CharField(help_text='Default Category Id', max_length=255, null=True)),
                ('invoice_lineitem_structure', models.CharField(choices=[('MULTIPLE', 'MULTIPLE'), ('SINGLE', 'SINGLE')], default='MULTIPLE', help_text='Invoice Lineitem Structure', max_length=255)),
                ('description_structure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Array of fields in memo', null=True, size=None)),
                ('emails_added', models.JSONField(default=list, help_text='Emails Selected For Email Notification', null=True)),
                ('created_at', models.DateField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateField(auto_now=True, help_text='Updated at datetime')),
                ('org', models.OneToOneField(help_text='Reference to Org Table', on_delete=django.db.models.deletion.PROTECT, to='orgs.org')),
            ],
            options={
                'db_table': 'travelperk_advance_settings',
            },
        ),
    ]
