# Generated by Django 3.1.14 on 2024-01-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelperk', '0009_travelperkprofilemapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='travelperkprofilemapping',
            unique_together=set(),
        ),
    ]
