# Generated by Django 3.1.14 on 2024-02-01 08:01

import apps.travelperk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelperk', '0011_travelperkadvancedsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelperk',
            name='onboarding_state',
            field=models.CharField(choices=[('CONNECTION', 'CONNECTION'), ('TRAVELPERK_PROFILE_MAPPINGS', 'TRAVELPERK_PROFILE_MAPPINGS'), ('ADVANCED_SETTINGS', 'ADVANCED_SETTINGS'), ('COMPLETE', 'COMPLETE')], default=apps.travelperk.models.get_default_onboarding_state, help_text='Onboarding State', max_length=255),
        ),
    ]
