# Generated by Django 3.1.14 on 2024-01-31 16:58

import apps.travelperk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelperk', '0012_auto_20240124_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelperkadvancedsetting',
            name='category_mappings',
            field=models.JSONField(default=apps.travelperk.models.default_category_mappings, help_text='Category mappings for travelperk'),
        ),
    ]
