# Generated by Django 3.1.14 on 2024-02-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelperk', '0012_travelperk_onboarding_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='org_id',
            new_name='org',
        ),
    ]
