# Generated by Django 3.1.14 on 2024-02-12 13:03

import apps.travelperk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelperk', '0013_auto_20240207_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='traveller_email',
            field=models.EmailField(help_text='Email address of the person who travelled.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='traveller_name',
            field=models.CharField(help_text='Name of the person who travelled.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelperkadvancedsetting',
            name='category_mappings',
            field=models.JSONField(default=apps.travelperk.models.default_category_mappings, help_text='Category mappings for travelperk'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='booker_email',
            field=models.EmailField(help_text='Email address of the person who booked the service.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='booker_name',
            field=models.CharField(help_text='Name of the person who booked the service.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='cost_center',
            field=models.CharField(help_text='Cost center associated with this line item.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='non_taxable_unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Non-taxable unit price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of the product or service.', null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total tax amount for this line item.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Tax percentage applied.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax_regime',
            field=models.CharField(help_text='Tax regime for this line item.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price of the product or service.', max_digits=10, null=True),
        ),
    ]
