name: Unit Test - API

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  pytest:
    runs-on: ubuntu-latest
    environment: CI Environment
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history for proper diff comparison

      - name: Bring up Services and Run Tests
        run: |
          docker compose -f docker-compose-pipeline.yml build
          docker compose -f docker-compose-pipeline.yml up -d
          docker compose -f docker-compose-pipeline.yml exec -T api pytest tests/ --cov --junit-xml=test-reports/report.xml --cov-report=xml --cov-report=term-missing --cov-fail-under=60 | tee pytest-coverage.txt
          echo "STATUS=$(cat pytest-coverage.txt | grep 'Required test' | awk '{ print $1 }')" >> $GITHUB_ENV
          echo "FAILED=$(cat test-reports/report.xml | awk -F'=' '{print $5}' | awk -F' ' '{gsub(/"/, "", $1); print $1}')" >> $GITHUB_ENV

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        if: ${{ always() && github.ref != 'refs/heads/master' }}
        with:
          create-new-comment: true
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./test-reports/report.xml

      - name: Perform coverage check
        shell: bash
        run: |
          set -o pipefail
          python -m pip install diff-cover
          
          # Ensure we have the base branch for comparison
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          
          # Generate diff coverage report with detailed output
          echo "=== Diff Coverage Report ===" > result.txt
          echo "Comparing: ${{ github.head_ref }} vs ${{ github.base_ref }}" >> result.txt
          echo "" >> result.txt
          
          # Run diff-cover with verbose output
          diff-cover coverage.xml \
            --compare-branch=${{ github.base_ref }} \
            --fail-under=98 \
            --show-uncovered \
            >> result.txt 2>&1 || true
          
          echo "" >> result.txt
          echo "=== Git Diff Summary ===" >> result.txt
          git diff --name-only ${{ github.base_ref }}..HEAD >> result.txt 2>&1 || true

      - name: Comment coverage check
        if: always()
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: result.txt

      - name: Stop Services
        run: docker compose -f docker-compose-pipeline.yml down

      - name: Evaluate Coverage
        if: ${{ (env.STATUS == 'FAIL') || (env.FAILED > 0) }}
        run: exit 1
