name: Continuous Deployment

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled]

jobs:
  staging_deploy:
    if: (github.event_name != 'pull_request') || (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'deploy')
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: push to dockerhub
        uses: fylein/docker-release-action@master
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          IMAGE_NAME: fyle_integration_settings-api
      - name: steps:
      - uses: actions/checkout@v2
      - name: Update image version
        run: |
          sed -i "s/image-name:.*/image-name:${{ github.sha }}/g" deployment/staging/controller.yml
          git add index.html
          git commit -m "Committing changes to index.html"
          git push
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Staging Deploy Status - ${{ job.status }}
          SLACK_TITLE: Deploy Integrations Settings API to Staging
          SLACK_ICON_EMOJI: ":pepeok:"
          SLACK_USERNAME: LOLO
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_FOOTER: ''